repoprovider = "Github"

[fmt]
  commands = ["gofmt -w"]
  perfile = false
  target = "."

  [fmt.dirs]
    whitelist = ["*vendor*",".git"]

  [fmt.files]
    blacklist = []
    whitelist = [".go$"]

[identity]
  envtoken = ""
  rawtoken = ""
  username = ""

[pr]
  base = "master"
  head = ""
  title = "gofmt: nice and clean. your's truly, the gofmt-att machine"

  [pr.body]
    file = ""
    text = "\nFormattered with :heart: by [gofmt-att](https://github.com/rotblauer/gofmt-att).\n\n> If we got it wrong, or there's a bug or something, please [let us know](https://github.com/rotblauer/gofmt-att/issues/new).\n"

[repos]
  isfork = false
  langauges = ["Go"]
  orderby = "desc"
  sortby = "updated"
  visibility = "visible"

[walk]

  [walk.humans]
    followers = 0.33333334
    following = 0.33333334
    orgmembers = 0.33333334

  [walk.repos]
    authored = 0.33333334
    forked = 0.33333334
    starred = 0.33333334

  [walk.weight]
    humans = 0.5
    repos = 0.5
